const EXT_TO_LOGO: Record<string, string> = {
  '.nes': 'nes.svg',
  '.sfc': 'snes.svg',
  '.smc': 'snes.svg',
  '.n64': 'n64.svg',
  '.z64': 'n64.svg',
  '.v64': 'n64.svg',
  '.gb': 'gb.svg',
  '.gba': 'gba.svg',
  '.gbc': 'gbc.svg',
  '.nds': 'nds.svg',
  '.3ds': 'n3ds.svg',
  '.iso': 'gc.svg',
  '.wbfs': 'wii.svg',
  '.rvz': 'gc.svg',
  '.gcm': 'gc.svg',
  '.bin': 'psx.svg',
  '.cue': 'psx.svg',
  '.chd': 'psx.svg',
  '.pbp': 'psp.svg',
  '.cso': 'psp.svg',
  '.gen': 'megadrive.svg',
  '.md': 'megadrive.svg',
  '.smd': 'megadrive.svg',
  '.sms': 'mastersystem.svg',
  '.gg': 'gamegear.svg',
  '.32x': 'sega32x.svg',
  '.gdi': 'dreamcast.svg',
  '.sat': 'saturn.svg',
  '.neo': 'neogeo.svg',
  '.ngcd': 'neogeocd.svg',
  '.ngp': 'ngp.svg',
  '.ngpc': 'ngpc.svg',
  '.7z': 'arcade.svg',
  '.zip': 'arcade.svg',
  '.a26': 'atari2600.svg',
  '.a52': 'atari5200.svg',
  '.a78': 'atari7800.svg',
  '.lnx': 'atarilynx.svg',
  '.st': 'atarist.svg',
  '.atr': 'atari800.svg',
  '.jag': 'atarijaguar.svg',
  '.col': 'colecovision.svg',
  '.int': 'intellivision.svg',
  '.vec': 'vectrex.svg',
  '.mx1': 'msx.svg',
  '.mx2': 'msx.svg',
  '.pce': 'pcengine.svg',
  '.pcecd': 'pcenginecd.svg',
  '.adf': 'amiga.svg',
  '.cd32': 'amigacd32.svg',
  '.d64': 'c64.svg',
  '.do': 'apple2.svg',
  '.fds': 'fds.svg',
  '.sg': 'sg-1000.svg',
  '.ps2': 'ps2.svg',
  '.wux': 'wiiu.svg',
  '.xex': 'xbox360.svg',
  '.xiso': 'xbox.svg',
  '.z80': 'zxspectrum.svg',
  '.ws': 'wonderswan.svg',
  '.wsc': 'wonderswancolor.svg',
  '.vb': 'virtualboy.svg',
  '.pokemini': 'pokemini.svg',
  '.unf': 'nes.svg',
  '.unif': 'nes.svg',
  '.fig': 'snes.svg',
  '.bs': 'snes.svg',
  '.swc': 'snes.svg',
  '.u1': 'n64.svg',
  '.gbs': 'gb.svg',
  '.gcz': 'gc.svg',
  '.ciso': 'gc.svg',
  '.cdi': 'dreamcast.svg',
  '.ccd': 'psx.svg',
  '.ecm': 'psx.svg',
  '.img': 'psx.svg',
  '.mdf': 'ps2.svg',
  '.gz': 'ps2.svg',
  '.cbn': 'psx.svg',
  '.psf': 'psx.svg',
  '.min': 'pokemini.svg',
  '.ngc': 'ngpc.svg',
  '.nsp': 'switch.svg',
  '.xci': 'switch.svg',
  '.nro': 'switch.svg',
  '.nso': 'switch.svg',
  '.nca': 'switch.svg',
  '.wud': 'wiiu.svg',
  '.rpx': 'wiiu.svg',
  '.app': 'n3ds.svg',
  '.cia': 'n3ds.svg',
  '.cci': 'n3ds.svg',
  '.cxi': 'n3ds.svg',
  '.3dsx': 'n3ds.svg',
  '.axis': 'n3ds.svg',
  '.dsi': 'nds.svg',
  '.ndd': 'n64dd.svg',
  '.d88': 'pc88.svg',
  '.d98': 'pc98.svg',
  '.hdi': 'pc98.svg',
  '.nhd': 'pc98.svg',
  '.hdd': 'pc98.svg',
  '.tfd': 'pc88.svg',
  '.2d': 'x1.svg',
  '.2hd': 'x1.svg',
  '.dx1': 'x1.svg',
  '.vpk': 'psvita.svg',
  '.ps3': 'ps3.svg',
  '.pkg': 'ps3.svg',
  '.rap': 'ps3.svg',
  '.wad': 'doom.svg',
  '.doom': 'doom.svg',
  '.iwad': 'doom.svg',
  '.svm': 'scummvm.svg',
  '.p8': 'pico8.svg',
  '.png': 'pico8.svg',
  '.tic': 'tic80.svg',
  '.wasm': 'wasm4.svg',
  '.nx': 'lowresnx.svg',
  '.mgw': 'gameandwatch.svg',
  '.chf': 'astrocade.svg',
  '.gam': 'vectrex.svg',
  '.sv': 'supervision.svg',
  '.ssd': 'bbcmicro.svg',
  '.crt': 'c64.svg',
  '.prg': 'c64.svg',
  '.x64': 'c64.svg',
  '.d71': 'c64.svg',
  '.d80': 'c64.svg',
  '.d81': 'c64.svg',
  '.d82': 'c64.svg',
  '.g64': 'c64.svg',
  '.gcr': 'c64.svg',
  '.t64': 'c64.svg',
  '.nib': 'apple2.svg',
  '.po': 'apple2.svg',
  '.2mg': 'apple2gs.svg',
  '.sna': 'amstradcpc.svg',
  '.cdt': 'amstradcpc.svg',
  '.cpr': 'amstradcpc.svg',
  '.kcr': 'amstradcpc.svg',
  '.tap': 'amstradcpc.svg',
  '.voc': 'amstradcpc.svg',
  '.tar': 'amstradcpc.svg',
  '.dsk': 'amstradcpc.svg',
  '.cas': 'amstradcpc.svg',
  '.scl': 'zxspectrum.svg',
  '.trd': 'zxspectrum.svg',
  '.tzx': 'zxspectrum.svg',
  '.p': 'zx81.svg',
  '.t81': 'zx81.svg',
  '.uae': 'amiga.svg',
  '.adz': 'amiga.svg',
  '.dms': 'amiga.svg',
  '.ipf': 'amiga.svg',
  '.hdf': 'amiga.svg',
  '.hdz': 'amiga.svg',
  '.lha': 'amiga.svg',
  '.m3u': 'amiga.svg',
  '.mds': 'amiga.svg',
  '.nrg': 'amiga.svg',
  '.rp9': 'amiga.svg',
  '.fdi': 'amiga.svg',
  '.msa': 'atarist.svg',
  '.stx': 'atarist.svg',
  '.atx': 'atari800.svg',
  '.car': 'atari5200.svg',
  '.dcm': 'atari5200.svg',
  '.abs': 'atarijaguar.svg',
  '.cof': 'atarijaguar.svg',
  '.j64': 'atarijaguar.svg',
  '.jcd': 'atarijaguarcd.svg',
  '.rom': 'colecovision.svg',
  '.1dd': 'adam.svg',
  '.cqi': 'adam.svg',
  '.cqm': 'adam.svg',
  '.ddp': 'adam.svg',
  '.dfi': 'adam.svg',
  '.hfe': 'adam.svg',
  '.imd': 'adam.svg',
  '.mfi': 'adam.svg',
  '.mfm': 'adam.svg',
  '.td0': 'adam.svg',
  '.wav': 'adam.svg',
  '.sgx': 'supergrafx.svg',
  '.toc': 'pcfx.svg',
  '.lst': 'naomi.svg',
  '.daphne': 'daphne.svg',
  '.m2v': 'daphne.svg',
  '.ogg': 'daphne.svg',
  '.com': 'dos.svg',
  '.exe': 'dos.svg',
  '.bat': 'dos.svg',
  '.conf': 'dos.svg',
  '.ins': 'dos.svg',
  '.raw': 'dos.svg',
  '.vhd': 'dos.svg',
};

const NAME_TO_LOGO: Record<string, string> = {
  'NES': 'nes.svg',
  'SNES': 'snes.svg',
  'Super Famicom': 'snes.svg',
  'Nintendo 64': 'n64.svg',
  'Game Boy': 'gb.svg',
  'Game Boy Advance': 'gba.svg',
  'Game Boy Color': 'gbc.svg',
  'Nintendo DS': 'nds.svg',
  'Nintendo 3DS': 'n3ds.svg',
  'GameCube': 'gc.svg',
  'Wii': 'wii.svg',
  'Wii U': 'wiiu.svg',
  'Nintendo Switch': 'switch.svg',
  'PlayStation': 'psx.svg',
  'PlayStation 2': 'ps2.svg',
  'PlayStation 3': 'ps3.svg',
  'PlayStation 4': 'ps4.svg',
  'PlayStation 5': 'ps5.svg',
  'PSP': 'psp.svg',
  'PlayStation Portable': 'psp.svg',
  'PlayStation Vita': 'psvita.svg',
  'Sega Genesis': 'megadrive.svg',
  'Mega Drive': 'megadrive.svg',
  'Sega Saturn': 'saturn.svg',
  'Dreamcast': 'dreamcast.svg',
  'Master System': 'mastersystem.svg',
  'Sega Master System': 'mastersystem.svg',
  'Game Gear': 'gamegear.svg',
  'Sega 32X': 'sega32x.svg',
  'Sega CD': 'segacd.svg',
  'Neo Geo': 'neogeo.svg',
  'Neo Geo CD': 'neogeocd.svg',
  'Neo Geo Pocket': 'ngp.svg',
  'Neo Geo Pocket Color': 'ngpc.svg',
  'Arcade': 'arcade.svg',
  'Arcade/MAME': 'arcade.svg',
  'PC': 'pc.svg',
  'Xbox': 'xbox.svg',
  'Xbox 360': 'xbox360.svg',
  'Xbox One': 'xboxone.svg',
  'ZX Spectrum': 'zxspectrum.svg',
  'Sinclair ZX Spectrum': 'zxspectrum.svg',
  'Amiga': 'amiga.svg',
  'Amiga CD32': 'amigacd32.svg',
  'Commodore 64': 'c64.svg',
  'Apple II': 'apple2.svg',
  'Atari 2600': 'atari2600.svg',
  'Atari 5200': 'atari5200.svg',
  'Atari 7800': 'atari7800.svg',
  'Atari Jaguar': 'atarijaguar.svg',
  'Atari Lynx': 'atarilynx.svg',
  'Atari ST': 'atarist.svg',
  'Atari 800': 'atari800.svg',
  'ColecoVision': 'colecovision.svg',
  'Intellivision': 'intellivision.svg',
  'Vectrex': 'vectrex.svg',
  'MSX': 'msx.svg',
  'PC Engine': 'pcengine.svg',
  'PC Engine CD': 'pcenginecd.svg',
  'Famicom Disk System': 'fds.svg',
  'Sega SG-1000': 'sg-1000.svg',
  'Virtual Boy': 'virtualboy.svg',
  'WonderSwan': 'wonderswan.svg',
  'WonderSwan Color': 'wonderswancolor.svg',
  'Pokémon Mini': 'pokemini.svg',
  'PlayStation/Sega': 'psx.svg',
  'Sony PlayStation': 'psx.svg',
  'Sony PSP': 'psp.svg',
  'PSX on PSP': 'psp.svg',
  'GameCube/Wii': 'gc.svg',
  'PlayStation/Dreamcast': 'psx.svg',
  'Sega': 'megadrive.svg',
  '3DO': '3do.svg',
  'Amstrad CPC': 'amstradcpc.svg',
  'BBC Micro': 'bbcmicro.svg',
  'Daphne': 'daphne.svg',
  'Doom': 'doom.svg',
  'DOS': 'dos.svg',
  'Fairchild Channel F': 'astrocade.svg',
  'Game & Watch': 'gameandwatch.svg',
  'LowRes NX': 'lowresnx.svg',
  'MAME': 'mame.svg',
  'PICO-8': 'pico8.svg',
  'PC-88': 'pc88.svg',
  'PC-98': 'pc98.svg',
  'PC-FX': 'pcfx.svg',
  'ScummVM': 'scummvm.svg',
  'Sharp X1': 'x1.svg',
  'TIC-80': 'tic80.svg',
  'TurboGrafx-16': 'tg16.svg',
  'TurboGrafx-CD': 'tg-cd.svg',
  'Watara Supervision': 'supervision.svg',
  'WASM-4': 'wasm4.svg',
  'ZX81': 'zx81.svg',
  'Sega NAOMI': 'naomi.svg',
  'Atari Jaguar CD': 'atarijaguarcd.svg',
  'SuperGrafx': 'supergrafx.svg',
  'SuFami Turbo': 'sufami.svg',
  'Coleco Adam': 'adam.svg',
  'Apple IIGS': 'apple2gs.svg',
  'Commodore VIC-20': 'vic20.svg',
  'Philips CD-i': 'cdimono1.svg',
  'FM Towns': 'fmtowns.svg',
  'Sharp X68000': 'x68000.svg',
};

export function getSystemLogo(ext?: string, name?: string): string | null {
  if (ext) {
    const lowerExt = ext.toLowerCase();
    if (EXT_TO_LOGO[lowerExt]) return EXT_TO_LOGO[lowerExt];
  }
  if (name) {
    if (NAME_TO_LOGO[name]) return NAME_TO_LOGO[name];
    const lower = name.toLowerCase();
    for (const [key, logo] of Object.entries(NAME_TO_LOGO)) {
      if (lower.includes(key.toLowerCase())) return logo;
    }
  }
  return null;
}

export const SYSTEM_LOGO_MAP = NAME_TO_LOGO;
