const EXT_TO_LOGO: Record<string, string> = {
  '.nes': 'nes.svg',
  '.sfc': 'snes.svg',
  '.smc': 'snes.svg',
  '.n64': 'n64.svg',
  '.z64': 'n64.svg',
  '.v64': 'n64.svg',
  '.gb': 'gb.svg',
  '.gba': 'gba.svg',
  '.gbc': 'gbc.svg',
  '.nds': 'nds.svg',
  '.3ds': 'n3ds.svg',
  '.iso': 'gc.svg',
  '.wbfs': 'wii.svg',
  '.rvz': 'gc.svg',
  '.gcm': 'gc.svg',
  '.bin': 'psx.svg',
  '.cue': 'psx.svg',
  '.chd': 'psx.svg',
  '.pbp': 'psp.svg',
  '.cso': 'psp.svg',
  '.gen': 'megadrive.svg',
  '.md': 'megadrive.svg',
  '.smd': 'megadrive.svg',
  '.sms': 'mastersystem.svg',
  '.gg': 'gamegear.svg',
  '.32x': 'sega32x.svg',
  '.gdi': 'dreamcast.svg',
  '.sat': 'saturn.svg',
  '.neo': 'neogeo.svg',
  '.ngcd': 'neogeocd.svg',
  '.ngp': 'ngp.svg',
  '.ngpc': 'ngpc.svg',
  '.7z': 'arcade.svg',
  '.zip': 'arcade.svg',
  '.a26': 'atari2600.svg',
  '.a52': 'atari5200.svg',
  '.a78': 'atari7800.svg',
  '.lnx': 'atarilynx.svg',
  '.st': 'atarist.svg',
  '.atr': 'atari800.svg',
  '.jag': 'atarijaguar.svg',
  '.col': 'colecovision.svg',
  '.int': 'intellivision.svg',
  '.vec': 'vectrex.svg',
  '.mx1': 'msx.svg',
  '.mx2': 'msx.svg',
  '.pce': 'pcengine.svg',
  '.pcecd': 'pcenginecd.svg',
  '.adf': 'amiga.svg',
  '.cd32': 'amigacd32.svg',
  '.d64': 'c64.svg',
  '.do': 'apple2.svg',
  '.fds': 'fds.svg',
  '.sg': 'sg-1000.svg',
  '.ps2': 'ps2.svg',
  '.wux': 'wiiu.svg',
  '.z80': 'zxspectrum.svg',
  '.ws': 'wonderswan.svg',
  '.wsc': 'wonderswancolor.svg',
  '.vb': 'virtualboy.svg',
  '.pokemini': 'pokemini.svg',
};

const NAME_TO_LOGO: Record<string, string> = {
  'NES': 'nes.svg',
  'SNES': 'snes.svg',
  'Super Famicom': 'snes.svg',
  'Nintendo 64': 'n64.svg',
  'Game Boy': 'gb.svg',
  'Game Boy Advance': 'gba.svg',
  'Game Boy Color': 'gbc.svg',
  'Nintendo DS': 'nds.svg',
  'Nintendo 3DS': 'n3ds.svg',
  'GameCube': 'gc.svg',
  'Wii': 'wii.svg',
  'Wii U': 'wiiu.svg',
  'Nintendo Switch': 'switch.svg',
  'PlayStation': 'psx.svg',
  'PlayStation 2': 'ps2.svg',
  'PlayStation 3': 'ps3.svg',
  'PlayStation 4': 'ps4.svg',
  'PlayStation 5': 'ps5.svg',
  'PSP': 'psp.svg',
  'PlayStation Vita': 'psvita.svg',
  'Sega Genesis': 'megadrive.svg',
  'Mega Drive': 'megadrive.svg',
  'Sega Saturn': 'saturn.svg',
  'Dreamcast': 'dreamcast.svg',
  'Master System': 'mastersystem.svg',
  'Sega Master System': 'mastersystem.svg',
  'Game Gear': 'gamegear.svg',
  'Sega 32X': 'sega32x.svg',
  'Sega CD': 'segacd.svg',
  'Neo Geo': 'neogeo.svg',
  'Neo Geo CD': 'neogeocd.svg',
  'Neo Geo Pocket': 'ngp.svg',
  'Neo Geo Pocket Color': 'ngpc.svg',
  'Arcade': 'arcade.svg',
  'Arcade/MAME': 'arcade.svg',
  'PC': 'pc.svg',
  'Xbox': 'xbox.svg',
  'Xbox 360': 'xbox360.svg',
  'Xbox One': 'xboxone.svg',
  'ZX Spectrum': 'zxspectrum.svg',
  'Amiga': 'amiga.svg',
  'Amiga CD32': 'amigacd32.svg',
  'Commodore 64': 'c64.svg',
  'Apple II': 'apple2.svg',
  'Atari 2600': 'atari2600.svg',
  'Atari 5200': 'atari5200.svg',
  'Atari 7800': 'atari7800.svg',
  'Atari Jaguar': 'atarijaguar.svg',
  'Atari Lynx': 'atarilynx.svg',
  'Atari ST': 'atarist.svg',
  'Atari 800': 'atari800.svg',
  'ColecoVision': 'colecovision.svg',
  'Intellivision': 'intellivision.svg',
  'Vectrex': 'vectrex.svg',
  'MSX': 'msx.svg',
  'PC Engine': 'pcengine.svg',
  'PC Engine CD': 'pcenginecd.svg',
  'Famicom Disk System': 'fds.svg',
  'Sega SG-1000': 'sg-1000.svg',
  'Virtual Boy': 'virtualboy.svg',
  'WonderSwan': 'wonderswan.svg',
  'WonderSwan Color': 'wonderswancolor.svg',
  'Pokémon Mini': 'pokemini.svg',
  'PlayStation/Sega': 'psx.svg',
  'Sony PlayStation': 'psx.svg',
  'Sony PSP': 'psp.svg',
  'PSX on PSP': 'psp.svg',
  'GameCube/Wii': 'gc.svg',
  'PlayStation/Dreamcast': 'psx.svg',
  'Sega': 'megadrive.svg',
};

export function getSystemLogo(ext?: string, name?: string): string | null {
  if (ext) {
    const lowerExt = ext.toLowerCase();
    if (EXT_TO_LOGO[lowerExt]) return EXT_TO_LOGO[lowerExt];
  }
  if (name) {
    if (NAME_TO_LOGO[name]) return NAME_TO_LOGO[name];
    const lower = name.toLowerCase();
    for (const [key, logo] of Object.entries(NAME_TO_LOGO)) {
      if (lower.includes(key.toLowerCase())) return logo;
    }
  }
  return null;
}

export const SYSTEM_LOGO_MAP = NAME_TO_LOGO;
