export const FANART_MAP: Record<string, string> = {
  '3DO Interactive Multiplayer': '',
  'Amiga': 'Amiga',
  'Amstrad CPC': 'Amstrad CPC',
  'Apple II': 'Apple II',
  'Apple IIGS': 'Apple IIGS',
  'Arcade': 'ArcadeMAME',
  'Atari 2600': 'Atari 2600',
  'Atari 5200': 'Atari 5200',
  'Atari 7800': 'Atari 7800',
  'Atari 800': 'Atari 800',
  'Atari Jaguar / CD': 'Atari Jaguar',
  'Atari Lynx': 'Atari Lynx',
  'Atari ST': 'Atari ST',
  'BBC Micro': 'BBC Micro',
  'Coleco Adam': 'ColecoVision',
  'ColecoVision': 'ColecoVision',
  'Commodore 64': 'Commodore 64',
  'Commodore Amiga': 'Amiga',
  'Commodore Amiga CD32': 'Amiga',
  'Commodore VIC-20': 'Commodore 64',
  'Daphne': 'Daphne',
  'DOS': 'DOS',
  'Fairchild Channel F': 'Fairchild Channel F',
  'Game & Watch': 'Game & Watch',
  'Game Boy': 'Game Boy',
  'Game Boy Advance': 'Game Boy Advance',
  'Game Boy Color': 'Game Boy Color',
  'GameCube': 'Nintendo GameCube',
  'Intellivision': 'Intellivision',
  'LowRes NX': 'LowRes NX',
  'MAME': 'ArcadeMAME',
  'MSX / MSX2': 'MSX',
  'Neo Geo': 'Neo Geo',
  'Neo Geo CD': 'Neo Geo',
  'Neo Geo Pocket / Color': 'Neo Geo Pocket',
  'NES': 'Nintendo Entertainment System',
  'Nintendo 3DS': 'Nintendo 3DS',
  'Nintendo 64 / 64DD': 'Nintendo 64',
  'Nintendo DS': 'Nintendo DS',
  'Nintendo Switch': '',
  'PC Engine / TurboGrafx-16': 'PC Engine',
  'PC Engine CD / TurboGrafx-CD': 'PC Engine',
  'PC-88': 'PC-88',
  'PC-98': 'PC-98',
  'PC-FX': 'PC-FX',
  'PICO-8': 'PICO-8',
  'PlayStation': 'PlayStation',
  'PlayStation 2': 'PlayStation 2',
  'PlayStation 3': 'PlayStation 3',
  'PlayStation Portable': 'PlayStation Portable',
  'PlayStation Vita': 'PlayStation Vita',
  'Pokémon Mini': 'Pokémon Mini',
  'ScummVM': 'ScummVM',
  'Sega 32X': 'Sega 32X',
  'Sega CD / Mega-CD': 'Sega Genesis',
  'Sega Dreamcast': 'Sega Saturn',
  'Sega Game Gear': 'Game Gear',
  'Sega Genesis / Mega Drive': 'Sega Genesis',
  'Sega Master System': 'Master System',
  'Sega NAOMI': 'Sega NAOMI',
  'Sega Saturn': 'Sega Saturn',
  'Sega SG-1000': 'SG-1000',
  'Sharp X1': 'Sharp X1',
  'Sharp X68000': 'Sharp X1',
  'SNES / Super Famicom': 'Super Nintendo',
  'SuperGrafx': 'PC Engine',
  'SuFami Turbo': 'Super Nintendo',
  'TIC-80': 'TIC-80',
  'Vectrex': 'Vectrex',
  'Virtual Boy': 'Virtual Boy',
  'WASM-4': 'WASM-4',
  'Watara Supervision': 'Watara Supervision',
  'Wii': 'Wii',
  'Wii U': 'Wii U',
  'WonderSwan / Color': 'WonderSwan',
  'Xbox': 'Xbox',
  'Xbox 360': 'Xbox 360',
  'ZX Spectrum': 'Sinclair ZX Spectrum',
  'Sinclair ZX81': 'Sinclair ZX81',
};

export function getFanartUrl(systemName: string): string | null {
  const key = FANART_MAP[systemName];
  if (!key) return null;
  return `system/fanart/${encodeURIComponent(key)}.jpg`;
}
